jobs:
  include:
    - stage: deploy
      go: 1.x
      language: minimal
      before_install:
        - docker build -f "docker/Dockerfile-build" -t factorio-server-manager docker
      script:
        - mkdir /home/travis/build/mroote/build
        - docker run -t -e FAC_BRANCH=$TRAVIS_BRANCH -v /home/travis/build/mroote/build:/build factorio-server-manager
        - mv /home/travis/build/mroote/build/factorio-server-manager-linux.zip /home/travis/factorio-server-manager-linux-${TRAVIS_TAG}.zip
        - mv /home/travis/build/mroote/build/factorio-server-manager-windows.zip /home/travis/factorio-server-manager-windows-${TRAVIS_TAG}.zip
      deploy:
        provider: releases
        api_key: "${GITHUB_TOKEN}"
        draft: true
        skip_cleanup: true
        on:
          tags: true
        file:
          - /home/travis/factorio-server-manager-linux-${TRAVIS_TAG}.zip
          - /home/travis/factorio-server-manager-windows-${TRAVIS_TAG}.zip